apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: backend-tests-go-yhcgwvvz
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/backend-tests-go-yhcgwvvz:0795a5e0e4daec2689327e438c4eb5dfcf434b35@sha256:9cdbec53c89fc788c99d5acbcdf626daba8f45af27138d09f8f4f21ba3a81366
          name: container-image
